### ISSUE TITLE
Bad error message for `1.+1`

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/JuliaSyntax.jl#57]
JuliaSyntax gives
![image](https://user-images.githubusercontent.com/11729272/185699194-e148e444-99dd-409b-90d3-9ee3769bf2ac.png)
While flisp gives
```
ERROR: syntax: invalid syntax "1.+"; add space(s) to clarify
Stacktrace:
 [1] top-level scope
   @ none:1
   ```

**Comment by c42f** [comment]
In the flisp parser this error arises from the lexer which is why it didn't get ported across in this case. I guess we've gotta figure out how to get error messages out of the tokenizer. Maybe out of band like ParseStream does it would be fine. Or invent a bunch of codes which can later be translated.

In this case the lexer is producing a bland `K"error"` which isn't much to go on downstream:

```julia
julia> collect(JuliaSyntax.Tokenize.tokenize("1.+1"))
4-element Vector{JuliaSyntax.Tokenize.Token}:
 0-1        error          
 2-2        +              
 3-3        Integer        
 4-3        EndMarker      

julia> dump(collect(JuliaSyntax.Tokenize.tokenize("1.+1"))[1])
JuliaSyntax.Tokenize.Token
  kind: JuliaSyntax.Kind K"error"
  startbyte: Int64 0
  endbyte: Int64 1
  dotop: Bool false
  suffix: Bool false
```
